---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(sf)
library(here)
library(leaflet)
```



```{r}
life_expectancy_data <- read_csv("~/public_health_dashboard/clean_data/life_expectancy_clean.csv")
```



```{r}
life_expectancy_data_2 <- life_expectancy_data %>%
  filter(age == "0 years" & date_code == "2017-2019")
```

```{r}
scotland_shape <- st_read(here("~/public_health_dashboard/clean_data/shape_data/pub_las.shp")) %>%
  st_simplify(dTolerance = 1000) %>%
  st_transform("+proj=longlat +datum=WGS84")
  
```


```{r}
scotland_shape
```

```{r}
view(scotland_shape)
```

```{r}
plot(scotland_shape)
```



```{r}
# Filter data for leaflet plot
test <- life_expectancy_data_2 %>%
  filter(measurement == "Count",
         sex == "Male") %>%
  group_by(local_authority) %>%
  # Join with shape data
  left_join(scotland_shape, by = c("local_authority" = "local_auth")) %>%
  # Convert to shape data from data frame
  st_as_sf()

test

life_exp_labels <- sprintf(
    "<strong>%s</strong><br/>%g deaths",
    test$local_authority, test$value
  ) %>% 
  lapply(htmltools::HTML)

bins <- c(0,50, 100, 200, 500, 1000, 2000)
pal <- colorBin("Purples", domain = test$value, bins = bins)


```



```{r}
leaflet(test, height = 600, width = 500) %>%
  setView(lng = -4.2026, lat = 57.8, zoom = 6, options = list()) %>%
  addPolygons()


  addPolygons(fillColor = ~pal(value),
              weight = 0.75,
              opacity = 1,
              color = "black",
              dashArray = "2",
              fillOpacity = 0.9,
              highlightOptions = highlightOptions(color = "white", weight = 2,
                                                  bringToFront = TRUE))
  
```
```{r}
leaflet(test)%>%
  addTiles() %>%
  addCircleMarkers(lng = ~location.longitude,
                   lat = ~location.latitude, radius = ~ amount/100, weight = 1)
```

