---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)

```

```{r}
life_expectancy_data <- read_csv("~/public_health_dashboard/clean_data/life_expectancy_clean.csv")
```

```{r}
life_expectancy_data_2 <- life_expectancy_data %>%
  filter(age == "0 years")
```


```{r}
life_expectancy_data_3 <- life_expectancy_data_2 %>%
  mutate(lower_confidence_limit = measurement == "95% Lower Confidence Limit")
```


```{r}
life_exp_a <- life_expectancy_data_2 %>%
  group_by(local_authority, date_code) %>%
  filter(measurement == "95% Lower Confidence Limit")


```


```{r}
life_exp_graph <- ggplot(life_expectancy_data_2, aes(x=local_authority, y=value, fill=sex)) + 
  geom_bar(stat="identity", color="black", width=0.7, position=position_dodge(width=0.9)) +
  geom_errorbar(aes(ymin=value, ymax=value), width=.2,
                 position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90))+
  labs(title="Life Expectancy In Scotland By Local Authority Area From 2009 to 2019", x="Local Authority Area", y = "Life Expectancy In Years")

print(life_exp_graph)



```

```{r}

# Layered bars chart

life_expectancy_test <- life_expectancy_data %>%
  filter(age == "0 years",
         local_authority == "City of Edinburgh") %>%
  mutate(measurement = factor(measurement, levels = c("95% Upper Confidence Limit",
                                                      "Count", "95% Lower Confidence Limit"))) %>%
  group_by(sex, measurement) %>%
  distinct() %>%
  summarise(value = mean(value))

xlim_low <- min(life_expectancy_test$value) - 0.5
xlim_high <- max(life_expectancy_test$value) + 0.5


ggplot(life_expectancy_test) + 
  geom_col(show.legend = FALSE,
           stat = "identity", 
           color = "black", 
           width = 2, 
           position = position_dodge(width = 0.0),
           alpha = 1.5,
           aes(y = sex, x = value, fill = measurement)) +
  labs(title="Life Expectancy In Scotland By Gender From 2009 to 2019", 
       y="Gender", 
       x = "Life Expectancy In Years") +
  coord_cartesian(xlim = c(xlim_low,xlim_high)) +
  scale_x_continuous(n.breaks = 10) +
  scale_fill_manual(values = bar_colours)


bar_colours <- c("white", "purple", "white")

```


