---
title: "Spatial Plotting test"
output: html_notebook
---

```{r}
# packages
library(tidyverse)
library(leaflet)
library(here)
library(sf)
```


```{r}
# load in data
drug_deaths <- read_csv(here("clean_data/drug_deaths_clean.csv"))
```

```{r}
# read in shape data
council_area_shapes <- st_read("clean_data/shape_data/pub_las.shp")

# simplify polygons SO IT WILL LOAD 
# then transform to correct type SO IT WILL LOAD
council_shapes_simple <- council_area_shapes %>% 
  st_simplify(dTolerance = 1000) %>%
  st_transform("+proj=longlat +datum=WGS84")

```

```{r}
# test plot
plot(council_shapes_simple[1])
```

```{r}
# Simple plot using ggplot

drug_deaths %>%
  filter(drug_name == "All drug-related deaths",
         council_area != "Scotland") %>%
  group_by(council_area) %>%
  summarise(num_deaths = sum(num_deaths)) %>%
  left_join(council_shapes_simple, by = c("council_area" = "local_auth")) %>%
  ggplot(aes(fill = num_deaths, geometry = geometry)) +
  geom_sf() +
  theme_void() +
  scale_fill_viridis_c(option = "turbo", trans = "log")
```

```{r}
# Filter data for leaflet plot
test <- drug_deaths %>%
  filter(drug_name == "All drug-related deaths",
         council_area != "Scotland") %>%
  group_by(council_area) %>%
  summarise(num_deaths = sum(num_deaths)) %>%
  # Join with shape data
  left_join(council_shapes_simple, by = c("council_area" = "local_auth")) %>%
  # Convert to shape data from data frame
  st_as_sf()

# Labels variable for leaflet plot
death_labels <- sprintf(
    "<strong>%s</strong><br/>%g deaths",
    test$council_area, test$num_deaths
  ) %>% 
  lapply(htmltools::HTML)

# Set bins and colour pallete for plot
bins <- c(0,50, 100, 200, 500, 1000, 2000)
pal <- colorBin("Purples", domain = test$num_deaths, bins = bins)


leaflet(test, height = 600, width = 500) %>%
  setView(lng = -4.2026, lat = 57.8, zoom = 6, options = list()) %>%
  addPolygons(fillColor = ~pal(num_deaths),
              weight = 0.75,
              opacity = 1,
              color = "black",
              dashArray = "2",
              fillOpacity = 0.9,
              highlightOptions = highlightOptions(color = "white", weight = 2,
                                                  bringToFront = TRUE),
  label = death_labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")) %>%
    addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
    position = "bottomright")
    
```

```{r}
drug_deaths %>%
  filter(drug_name == "All drug-related deaths",
         council_area == "Scotland") %>%
  ggplot() +
    aes(x = year, y = num_deaths) +
    geom_line() +
    geom_point() +
    scale_x_continuous(n.breaks = 10) +
    scale_y_continuous(n.breaks = 8)
    
    
```

